#!/usr/bin/env ruby
# Inserts "last modified" metadata into Markdown documents.
#
# This script is to be used as part of Git filter commands (see
# <https://git-scm.com/docs/gitattributes#_code_filter_code> for more
# information). Add the following to ".git/config":
#
#   [filter "addlastupdated"]
#     smudge = ./addlastupdated %f
#     clean = ./addlastupdated
#
# This file was written by Damien Dart, <damiendart@pobox.com>. This is
# free and unencumbered software released into the public domain. For
# more information, please refer to the accompanying "UNLICENCE" file.

if ARGV.empty?
  last_updated = '_See accompanying `addlastupdated` script._'
else
  last_updated =
    '<a data-timestamp="' + `git log -n 1 --pretty=format:%at #{ARGV[1]}` +
    '" href="https://github.com/damiendart/notes/commit/' +
    `git log -n 1 --pretty=format:%H #{ARGV[1]}` + '">' +
    `git log -n 1 --date=short --pretty=format:%ad #{ARGV[1]}` + '</a>'
end

puts STDIN.read.gsub(
  /\*\*Last Updated\*\*:.*$/,
  '**Last Updated**: ' + last_updated
)
